version: "3.9"

volumes:
  redis-data:

services:
  redis:
    image: redislabs/redismod:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  ui:
    build:
      context: .
      args: &environment
        API_URL: https://test.quid.io/api
        USDT_CONTRACT_ID: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
        CONTRACT_ID: "0x75781C26A8CA4d9cBF6268a9B05c657EF6149C5f"
        NETWOKR: mainnet
        INFURA_KEY: "d5fa11d013fc419badcb1ad40aec0e97"
    environment:
      REDIS_CONNECTION_STRING: redis://redis/0
      NEXT_PUBLIC_CONTRACT_ID: "0xA0Dc23FA9F42146E62E027C50f866d8Bdcc46a8a"
      NEXT_PUBLIC_INFURA_KEY: "d5fa11d013fc419badcb1ad40aec0e97"
      NEXT_PUBLIC_USDT_CONTRACT_ID: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
      NEXT_PUBLIC_NETWOKR: mainnet
      NEXT_PUBLIC_OWNER_ID: 0x42cc020Ef5e9681364ABB5aba26F39626F1874A4

    ports:
      - "3000:3000"
    depends_on:
      - redis

  nginx:
    image: linuxserver/swag:1.20.0
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - URL=test.quid.io
      - VALIDATION=http
      - STAGING=false
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    volumes:
      - "/home/ec2-user/mp/docker/linuxserver/default:/config/nginx/site-confs/default"
