version: '3.7'

services:
  redis:
    image: redislabs/redisearch:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    environment:
      - REDIS_CONNECTION_STRING=redis://localhost:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis

volumes:
  redis-data:
