version: "3.9"

volumes:
  redis-data:
  static-data:

services:
  redis:
    restart: always
    image: redislabs/redismod:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  ui:
    restart: always
    build:
      context: .
      args: &environment
        API_URL: https://ibo.quid.io/api
        USDT_CONTRACT_ID: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
        CONTRACT_ID: "0x630B1b4Bc4B986E34f3fC752ac12EC67286EfBbD"
        NETWOKR: mainnet
        INFURA_KEY: "f10e928c34314bdeb7198c2e738f3efa"
    environment:
      REDIS_CONNECTION_STRING: redis://redis/0
      NEXT_PUBLIC_CONTRACT_ID: "0x630B1b4Bc4B986E34f3fC752ac12EC67286EfBbD"
      NEXT_PUBLIC_INFURA_KEY: "f10e928c34314bdeb7198c2e738f3efa"
      NEXT_PUBLIC_USDT_CONTRACT_ID: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      NEXT_PUBLIC_API_URL: https://ibo.quid.io/api
      NEXT_PUBLIC_NETWOKR: mainnet

    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - static-data:/static-data:rw
      - ./entrypoint.sh:/app/entrypoint.sh

  nginx:
    image: linuxserver/swag:1.20.0
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - URL=ibo.quid.io
      - VALIDATION=http
      - STAGING=false
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    volumes:
      - "/home/ec2-user/qdo-app/docker/linuxserver/default:/config/nginx/site-confs/default"
      - static-data:/static-data
    depends_on:
      - ui
