apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quid-ui.fullname" . }}
  labels:
    {{- include "quid-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "quid-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quid-ui.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "quid-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.container.livenessProbe }}
          livenessProbe:
            {{ toYaml .Values.container.livenessProbe | trim | nindent 12 }}
          {{- end }}
          {{- if .Values.container.readinessProbe }}
          readinessProbe:
            {{ toYaml .Values.container.readinessProbe | trim | nindent 12 }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: quid-ui
          - secretRef:
              name: redis-secret
          - configMapRef:
              name: {{ .Release.Name }}-version
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
