{{- if .Values.ingress.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-development"
spec:
  ingressClassName: {{ default "nginx" .Values.ingress.class }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "quid-ui.fullname" . }}-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /
          backend:
            service:
              name: {{ include "quid-ui.fullname" . }}
              port:
                number: {{ .Values.service.port }}
          pathType: ImplementationSpecific

{{- end }}
